/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author KOBBY LEO
 */
public class AddMedicine extends javax.swing.JFrame {

    String numberPattern = "^[0-9]*$";
    public int checkMedID = 0;

    /**
     * Creates new form AddMedicine
     */
    public AddMedicine() {
        initComponents();
        iconLabel.setVisible(false);
        setLocationRelativeTo(null);

        Image icon = new ImageIcon(this.getClass().getResource("/logo.png")).getImage();
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MedID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        MedName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CompName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Quantity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        PPunit = new javax.swing.JTextField();
        btnAddMed = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        iconLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 68, 1194, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD MEDICINE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 388, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Medicine ID");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        MedID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MedID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MedIDKeyReleased(evt);
            }
        });
        jPanel1.add(MedID, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 190, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Medicine Name");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        MedName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MedName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedNameActionPerformed(evt);
            }
        });
        jPanel1.add(MedName, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 191, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Company Name");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        CompName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(CompName, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 191, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Quantity");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

        Quantity.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 190, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Price Per Unit ");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, -1, -1));

        PPunit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(PPunit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 190, -1));

        btnAddMed.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnAddMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save_30px.png"))); // NOI18N
        btnAddMed.setText("SAVE");
        btnAddMed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMedMouseClicked(evt);
            }
        });
        btnAddMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMedActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, -1, 50));

        logout.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout_rounded_left_60px.png"))); // NOI18N
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, -1, 60));

        Exit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/running_60px.png"))); // NOI18N
        Exit.setText("EXIT");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 580, 170, 60));

        iconLabel.setText("jLabel9");
        jPanel1.add(iconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, -1, 20));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back_30px.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Do you want to exit the Application?", "select option", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_ExitActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout from the Application?", "select option", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION) {
            Login obj = new Login();
            obj.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void btnAddMedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMedMouseClicked

        String medId = MedID.getText();
        String medName = MedName.getText();
        String compName = CompName.getText();
        String quantity = Quantity.getText();
        String price = PPunit.getText();

        if (medId.equals("")) {
            JOptionPane.showMessageDialog(null, "Medicine ID is required ");
        }
        else if(checkMedID==1){
            JOptionPane.showMessageDialog(null, "Meddicine ID already exist");
        }
        else if (medName.equals("")) {
            JOptionPane.showMessageDialog(null, "Medicine Name is required ");
        } else if (compName.equals("")) {
            JOptionPane.showMessageDialog(null, "Company Name is required ");
        } else if (quantity.equals("")) {
            JOptionPane.showMessageDialog(null, "Medicine Quantity is required ");
        } else if (price.equals("")) {
            JOptionPane.showMessageDialog(null, "Medicine Price Per Unit  is required ");
        } else if (!price.matches(numberPattern)) {
            JOptionPane.showMessageDialog(null, "Medicine Price Per Unit is Invalid ");
        } else if (!quantity.matches(numberPattern)) {
            JOptionPane.showMessageDialog(null, "Medicine Quantity is Invalid ");
        } else {

            try {

                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3308/Pharmacy", "root", "2019");
                //   Statement stm = (Statement)con.createStatement();
                String sql = "Insert into Medicine(Medicine_UniqueID,MedName,CompName,Quantity,PricePer_Unit)values(?,?,?,?,?)";

                PreparedStatement pstm = con.prepareStatement(sql);
                pstm.setString(1, medId);
                pstm.setString(2, medName);
                pstm.setString(3, compName);
                pstm.setString(4, quantity);
                pstm.setString(5, price);

                pstm.executeUpdate();
                JOptionPane.showMessageDialog(null, "Medicine Added Successfully");
                setVisible(false);
                new AddMedicine().setVisible(true);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }

    }//GEN-LAST:event_btnAddMedMouseClicked

    private void MedNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedNameActionPerformed

    private void MedIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MedIDKeyReleased
        // TODO add your handling code here:
        String medId = MedID.getText();

        if (!medId.equals("")) {
            iconLabel.setVisible(true);
            iconLabel.setIcon(new ImageIcon("src\\icons\\done_20px.png"));
            iconLabel.setText("");
            checkMedID = 0;

            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3308/Pharmacy", "root", "2019");
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("Select * from Medicine WHERE Medicine_UniqueID='" +medId+ "'");
                while (rs.next()) {
                    checkMedID = 1;
                    iconLabel.setIcon(new ImageIcon("src\\icons\\close_20px.png"));
                    iconLabel.setText("");

                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }

        }

    }//GEN-LAST:event_MedIDKeyReleased

    private void btnAddMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddMedActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        Dashboard obj = new Dashboard();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CompName;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField MedID;
    private javax.swing.JTextField MedName;
    private javax.swing.JTextField PPunit;
    private javax.swing.JTextField Quantity;
    private javax.swing.JButton btnAddMed;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
