/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy;

import java.awt.Image;
import java.sql.DriverManager;
//import com.sun.jdi.connect.spi.Connection;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.*;
import javax.swing.ImageIcon;
 import javax.swing.JOptionPane;
/**
 *
 * @author KOBBY LEO
 */
public class Login extends javax.swing.JFrame {
PreparedStatement pst = null;
ResultSet rs = null;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        
        
        Image icon = new ImageIcon(this.getClass().getResource("/logo.png")).getImage();
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUn = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSc = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        BtnLogin = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        BtnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnSubmit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Combo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtUn, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 187, 133, -1));

        txtpass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        jPanel1.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 264, 133, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Forgot Password or User Name? ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 416, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Enter Secret Code");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 460, -1, -1));

        txtSc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScActionPerformed(evt);
            }
        });
        jPanel1.add(txtSc, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 461, 140, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 204));
        jLabel1.setText("Login Page");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 15, 247, -1));

        BtnLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnLogin.setText("Login");
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 345, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 77, 241, 13));

        BtnCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnCancel.setText("Cancel");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 345, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("UserName");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 186, -1, -1));

        BtnSubmit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnSubmit.setText("Submit");
        BtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 531, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 263, -1, -1));

        Combo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Pharmacist" }));
        Combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboActionPerformed(evt);
            }
        });
        jPanel1.add(Combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 117, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtScActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScActionPerformed

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
       
        String un = txtUn.getText();
        String pass = txtpass.getText();
         Combo.getSelectedItem();
         
        int temp = 0;
        {
          try
            // Code for Admin login
            {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3308/Pharmacy","root", "2019");
                String query = "SELECT * FROM Users WHERE UserName=? and Password=? and Role=?";
           pst = con.prepareStatement(query);
          pst.setString(1, txtUn.getText());
       
           pst.setString(2, txtpass.getText());
           pst.setString(3, String.valueOf(Combo.getSelectedItem()));
      
                rs = pst.executeQuery();
                temp =1;
                if(rs.next())
                {

                    JOptionPane.showMessageDialog(this, "Connected Successfully  ");
                    if (Combo.getSelectedIndex()==0){
                    AdminDashboard obj = new AdminDashboard(un);
                    obj.setVisible(true);
                    this.setVisible(false);   
                     dispose();
                    }
                    else{
                         Dashboard obj = new Dashboard();
                    obj.setVisible(true);
                    this.setVisible(false);   
                     dispose();
                    }
                 
                }
                else if(un.isEmpty() || pass.isBlank())
                {
                    JOptionPane.showMessageDialog(null, "Please Enter all fields");
                }

                else
                {
                    JOptionPane.showMessageDialog(null, "UserName or Password is incorrect");
                    txtUn.setText("");
                    txtpass.setText("");
                }
                

            }

            catch(Exception ex)
            {

                JOptionPane.showMessageDialog(null, ex.getMessage());
            }

        }
    }//GEN-LAST:event_BtnLoginActionPerformed

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        txtUn.setText("");
        txtpass.setText("");
    }//GEN-LAST:event_BtnCancelActionPerformed

    private void BtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubmitActionPerformed
        String sc = txtSc.getText();
        String newline=  System.lineSeparator();
        if(sc.equals("2022")){
            JOptionPane.showMessageDialog(null, "Your UserName is : admin" +newline+  "Password is : 2019" );
        }
        else if(sc.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter Secret Code");

        }
        else
        {
            JOptionPane.showMessageDialog(null, "Wrong Secret Code! ");

        }
        txtSc.setText("");
    }//GEN-LAST:event_BtnSubmitActionPerformed

    private void ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboActionPerformed

    }//GEN-LAST:event_ComboActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnLogin;
    private javax.swing.JButton BtnSubmit;
    private javax.swing.JComboBox<String> Combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField txtSc;
    private javax.swing.JTextField txtUn;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables
}
